### ISSUE TITLE
unsafe sscanf use

### ISSUE THREAD

**Issue by batpudding** [TrilbyWhite/swifer#4]
scanf will overflow a string with ease.  There are very few times where it's a good idea to use scanf without a string length.

Option 1:
http://stackoverflow.com/questions/1621394/how-to-prevent-scanf-causing-a-buffer-overflow-in-c

  #define MAX_LEN 16
  #define STR1(x)  #x
  #define STR(x)  STR1(x)
  char val[MAX_LEN + 1];
  sscanf(buf, "%" STR(MAX_LEN) "s", val);

Option 2:
Another possibility that doesn't include using the double expansion mentioned above is to parse the line using:
  for ( i=0; i<strlen( input ); i++ )

Option 3:
Require that the permissions on the config file be read-only for group and world.  This isn't great, but at least it prevents privilege escalation.

**Comment by TrilbyWhite** [comment]
the string 'val' is the same length as 'buf', so in this case there is no way it can overflow.  What is left for the %s format specifier will be shorter than 'buf' and thus shorter than 'val'.  These are sscanf functions, not fscanf or scanf: they read from a string of a finite length (MAX_LINE in this case).

**Comment by batpudding** [comment]
Oh dur, making line and val the same length didn't even cross my mind.

I double checked and as long as fgets() isn't NULL, it terminates the string, so even if the line in the file is too long, it will be fine.

fgets also includes the terminator in the size argument, so you can safely give it MAX_LINE+1.  Not much of a deal, but you could do this if you wanted to:
  line[MAX_LINE+1]; fgets(line, MAX_LINE+1, FILE);
